"""
test_context_document_live.py (v2)

FIX from the previous version: report content is now generated by calling
the REAL build_full_report() (same function the eventual Streamlit app
will call), not a hardcoded string copy-pasted to match it. If severity.py
or explainer.py change later, this test automatically reflects that --
it can no longer silently drift out of sync.

Run from inside agent/ (imports are local to this folder already).
"""
import sys
import os

AGENT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "agent")
sys.path.insert(0, AGENT_DIR)

from datahub.sdk.main_client import DataHubClient
from datahub_agent_context.context import DataHubContext

from parse_migration import parse_migration
from report_builder import build_full_report, get_downstream_assets
from severity import classify_migration
from severity_rollup import compute_overall_severity
from write_back_context_document import write_back_context_document

client = DataHubClient(server="http://localhost:8081", token="")

TABLE_URN = "urn:li:dataset:(urn:li:dataPlatform:postgres,orders,PROD)"

TEST_SQL = """
ALTER TABLE orders
  DROP COLUMN shipping_address,
  ADD COLUMN loyalty_points INT;
"""

with DataHubContext(client):
    print("=" * 70)
    print("STEP 1: parse + build the REAL report (not hardcoded)")
    print("=" * 70)
    parsed = parse_migration(TEST_SQL)
    report_content = build_full_report(
        table=parsed["table"],
        table_urn=TABLE_URN,
        operations=parsed["operations"],
    )
    print(report_content)

    print()
    print("=" * 70)
    print("STEP 2: compute overall severity (real, from classify_migration)")
    print("=" * 70)
    downstream_assets = get_downstream_assets(TABLE_URN)
    downstream_count = len(downstream_assets)
    downstream_lookup = {
        op.get("column"): downstream_count for op in parsed["operations"] if op.get("column")
    }
    pii_lookup = {op.get("column"): False for op in parsed["operations"] if op.get("column")}
    classified = classify_migration(parsed["operations"], downstream_lookup, pii_lookup)
    overall_severity = compute_overall_severity(classified)
    print(f"Overall severity: {overall_severity}")

    print()
    print("=" * 70)
    print("STEP 3: write the REAL report content as a Context Document")
    print("=" * 70)
    result = write_back_context_document(
        table=parsed["table"],
        table_urn=TABLE_URN,
        report_content=report_content,
        overall_severity=overall_severity,
        dry_run=False,
    )
    print()
    print(f"Result: {result}")